version: 2

models:
  - name: stg_locations
    description: "Cleaned city metadata and coordinates"
    columns:
      - name: city_name
        tests: [not_null, unique]

  - name: stg_weather_daily
    description: "Daily historical weather per city"
    columns:
      - name: city_name
        tests: [not_null]
      - name: date
        tests: [not_null]

  - name: stg_forecast_daily
    description: "Daily weather forecast per city"
    columns:
      - name: city_name
        tests: [not_null]
      - name: date
        tests: [not_null]

  - name: stg_air_quality_hourly
    description: "Hourly air quality per city"
    columns:
      - name: city_name
        tests: [not_null]
      - name: timestamp
        tests: [not_null]
